[github]

# Information for securely interacting with GitHub. These are found/generated
# under <https://github.com/settings/applications>.

# A GitHub personal access token
access_token = ""

# A GitHub oauth application for this instance of homu:
app_client_id = ""
app_client_secret = ""

[web]

# The port homu listens on
port = 54856

# An example configuration for repository (there can be many of these)
[repo.NAME]

# github.com/<owner>/<name>
owner = ""
name = ""

# who has r+ rights? The keyword "ALL" may be used instead of a list.
reviewers = ["barosl", "graydon"]

## branch names (these settings here are the defaults)
#[repo.NAME.branch]
#
#auto = "auto"
#try = "try"
#rollup = "rollup"

[repo.NAME.github]

# arbitrary secret (e.g. openssl rand -hex 20)
secret = ""

## Use buildbot for running tests
#[repo.NAME.buildbot]
#
#url = ""
#secret = ""
#
#builders = ["auto-linux", "auto-mac"]
#try_builders = ["try-linux", "try-mac"]
#
#username = ""
#password = ""

## Use travis for running tests
#[repo.NAME.travis]
#
## found under <https://travis-ci.org/profile/info>.
#token = ""

## Use jenkins or solano for running tests.
#[repo.NAME.testrunners]
#builders = ['jenkins', 'solano']

## Who issues PRs to trigger Solano?
#[trigger_author]
#name = "GITHUB USERNAME"
#email = "GITHUB EMAIL ADDRESS"

## Use the Status API
#[repo.NAME.status]
#
## String label set by status updates
#context = ""

## Builds can be triggered when a code_reviewer status goes green.
#[code_reviewer]
#name = "STATUS CONTEXT"
#target_branch_whitelist = "CSV BRANCH NAMES"
